[CI] Temporarily suspend clang-format check
Clang-format is causing some kind of tool dependency issue and breaking
all CI.  Remove it temporarily so other changes can make progress.

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -25,7 +25,7 @@ jobs:
     vmImage: "ubuntu-latest"
   steps:
   - bash: |
-      sudo apt-get install -y python3 python3-pip build-essential srecord python3-setuptools zlib1g-dev libusb-1.0 clang-format
+      sudo apt-get install -y python3 python3-pip build-essential srecord python3-setuptools zlib1g-dev libusb-1.0
       sudo pip3 install -U -r python-requirements.txt
     displayName: 'Install dependencies'
 
@@ -33,7 +33,8 @@ jobs:
       python3 --version
       yapf --version
       isort --version
-      clang-format -version
+
+#      clang-format -version
     displayName: 'Display tool versions'
 
 #   XXX: Python lint checks are disabled until Issue #313 is resolved
@@ -50,23 +51,23 @@ jobs:
     condition: always()
     displayName: 'Ensure all generated files are clean and up-to-date'
 
-  - bash: |
-      # XXX: As of today, task.logissue comments with 'sourcepath' set don't
-      # get reported to GitHub Checks annotations. Upstream bug report:
-      # https://developercommunity.visualstudio.com/content/problem/689794/pipelines-logging-command-logissue-does-not-report.html
-      #echo "##vso[task.issue type=error;sourcepath=/azure-pipelines.yml;linenumber=45;columnnumber=1;code=100;]Found something that could be a problem."
-      fork_origin=$(git merge-base --fork-point origin/master)
-      changed_files=$(git diff --name-only $fork_origin | grep -v /vendor/)
-      test -z $changed_files || git diff -U0 $fork_origin $changed_files | clang-format-diff -p1 | tee clang-format-output
-      if [ -s clang-format-output ]; then
-        echo -n "##vso[task.logissue type=error]"
-        echo "C/C++ lint failed. Use 'util/run-clang-format.sh' or 'git clang-format' to format the code."
-        exit 1
-      fi
-    # This check is not idempotent, but checks changes to a base branch.
-    # Run it only on pull requests.
-    condition: eq(variables['Build.Reason'], 'PullRequest')
-    displayName: 'Use clang-format to check C/C++ coding style'
+##  - bash: |
+##      # XXX: As of today, task.logissue comments with 'sourcepath' set don't
+##      # get reported to GitHub Checks annotations. Upstream bug report:
+##      # https://developercommunity.visualstudio.com/content/problem/689794/pipelines-logging-command-logissue-does-not-report.html
+##      #echo "##vso[task.issue type=error;sourcepath=/azure-pipelines.yml;linenumber=45;columnnumber=1;code=100;]Found something that could be a problem."
+##      fork_origin=$(git merge-base --fork-point origin/master)
+##      changed_files=$(git diff --name-only $fork_origin | grep -v /vendor/)
+##      test -z $changed_files || git diff -U0 $fork_origin $changed_files | clang-format-diff -p1 | tee clang-format-output
+##      if [ -s clang-format-output ]; then
+##        echo -n "##vso[task.logissue type=error]"
+##        echo "C/C++ lint failed. Use 'util/run-clang-format.sh' or 'git clang-format' to format the code."
+##        exit 1
+##      fi
+##    # This check is not idempotent, but checks changes to a base branch.
+##    # Run it only on pull requests.
+##    condition: eq(variables['Build.Reason'], 'PullRequest')
+##    displayName: 'Use clang-format to check C/C++ coding style'
 
   - bash: |
       commit_range=$(git merge-base --fork-point origin/master)..HEAD
