[release] Set up release pipeline configuration
Signed-off-by: Miles Dai <milesdai@google.com>

diff --git a/release/azure-pipelines-release.yml b/release/azure-pipelines-release.yml
--- a/release/azure-pipelines-release.yml
+++ b/release/azure-pipelines-release.yml
@@ -15,9 +15,22 @@ schedules:
     - "master"
   always: True
 
+# To run on a schedule, PR and other triggers must be disabled
+pr: none
+trigger: none
+
 variables:
-- name: pkg_path
-  value: ""
+  # If updating VERILATOR_VERSION, TOOLCHAIN_VERSION or RUST_VERSION, update the
+  # definitions in util/container/Dockerfile as well.
+  VERILATOR_VERSION: 4.210
+  TOOLCHAIN_PATH: /opt/buildcache/riscv
+  VERIBLE_VERSION: v0.0-2135-gb534c1fe
+  RUST_VERSION: 1.60.0
+    # Release tag from https://github.com/lowRISC/lowrisc-toolchains/releases
+  TOOLCHAIN_VERSION: 20220210-1
+    # This controls where builds happen, and gets picked up by build_consts.sh.
+  BUILD_ROOT: $(Build.ArtifactStagingDirectory)
+  VIVADO_VERSION: "2020.2"
 
 jobs:
 - job: checkout
@@ -34,19 +47,57 @@ jobs:
     artifact: opentitan-repo
     displayName: "Upload repository"
 
-- job: package
-  displayName: "Create the release package"
-  timeoutInMinutes: 180
+- job: build_release
+  displayName: "Create the OpenTitan release"
+  timeoutInMinutes: 240
   dependsOn: checkout
   pool: ci-public
   steps:
-  - template: ci/checkout-template.yml
+  - template: ../ci/checkout-template.yml
+  - template: ../ci/install-package-dependencies.yml
   - bash: |
-      ci/bazelisk.sh build release
+      set -ex
+      trap 'get_logs' EXIT
+      get_logs() {
+        # Export the Vivado logs
+        mkdir -p $OBJ_DIR/hw/top_earlgrey/standard-release
+        mkdir -p $OBJ_DIR/hw/top_earlgrey/chip_earlgrey_cw310_hyperdebug-release/
+        cp -rLt $OBJ_DIR/hw/top_earlgrey/standard-release \
+          $($REPO_TOP/bazelisk.sh outquery-all //hw/bitstream/vivado:fpga_cw310)
+        cp -rLt $OBJ_DIR/hw/top_earlgrey/chip_earlgrey_cw310_hyperdebug-release/ \
+          $($REPO_TOP/bazelisk.sh outquery-all //hw/bitstream/vivado:fpga_cw310_hyperdebug)
+      }
+
+      . util/build_consts.sh
+      module load "xilinx/vivado/$(VIVADO_VERSION)"
+      # Build the release package
+      # --jobs=1 is necessary due to resource constraints on the build machine.
+      # Running multiple Vivado and Verilator build jobs simultaneously can
+      # cause Synthesis failures
+      ci/bazelisk.sh build release --jobs=1
+
+      # Set the package-path variable for the artifact-publishing step
       PKG_PATH=$(./bazelisk.sh outquery //release:opentitan)
       echo $PKG_PATH
-      echo "##vso[task.setvariable variable=pkg_path]$(PKG_PATH)"
+      echo "##vso[task.setvariable variable=pkg_path]$PKG_PATH"
     displayName: "Build Bazel release package"
+
+  - bash: |
+      . util/build_consts.sh
+      echo "Synthesis log"
+      cat $OBJ_DIR/hw/top_earlgrey/standard-release/build.fpga_cw310/synth-vivado/lowrisc_systems_chip_earlgrey_cw310_0.1.runs/synth_1/runme.log || true
+      echo "Implementation log"
+      cat $OBJ_DIR/hw/top_earlgrey/standard-release/build.fpga_cw310/synth-vivado/lowrisc_systems_chip_earlgrey_cw310_0.1.runs/impl_1/runme.log || true
+    displayName: "Display standard bitstream synth and impl logs"
+
+  - bash: |
+      . util/build_consts.sh
+      echo "Synthesis log"
+      cat $OBJ_DIR/hw/top_earlgrey/chip_earlgrey_cw310_hyperdebug-release/build.fpga_cw310/synth-vivado/lowrisc_systems_chip_earlgrey_cw310_0.1.runs/synth_1/runme.log || true
+      echo "Implementation log"
+      cat $OBJ_DIR/hw/top_earlgrey/chip_earlgrey_cw310_hyperdebug-release/build.fpga_cw310/synth-vivado/lowrisc_systems_chip_earlgrey_cw310_0.1.runs/impl_1/runme.log || true
+    displayName: "Display hyperdebug bitstream synth and impl logs"
+
   - publish: $(pkg_path)
-    artifact: opentitan-artifacts
-    displayName: "Upload artifacts"
+    artifact: opentitan-release
+    displayName: "Upload release artifacts"
