[ci] DONT_MERGE
Just executing usb hub power cycle

Signed-off-by: Michael Gautschi <mgautschi@lowrisc.org>

diff --git a/.github/workflows/fpga.yml b/.github/workflows/fpga.yml
--- a/.github/workflows/fpga.yml
+++ b/.github/workflows/fpga.yml
@@ -144,28 +144,28 @@ jobs:
           sudo uhubctl -p all -a cycle || echo "::warning::uhubctl exited $? (known segfault: mvp/uhubctl#539)"
           sudo uhubctl -p 4 -a off || echo "::warning::uhubctl exited $? (known segfault: mvp/uhubctl#539)"
 
-      - name: Update hyperdebug firmware
-        if: inputs.interface == 'hyper310' || inputs.interface == 'cw340'
-        run: |
-          ./bazelisk.sh run \
-              //sw/host/opentitantool:opentitantool -- \
-              --interface=hyperdebug_dfu transport update-firmware
-
-      - name: Execute tests
-        run: |
-          . util/build_consts.sh
-          module load "xilinx/vivado/${{ inputs.vivado_version }}"
-
-          cache_test_results="--cache_test_results=${{ inputs.cache_test_results }}"
-
-          # Run FPGA tests
-          if [[ -s "$target_pattern_file" ]]; then
-            ci/scripts/run-fpga-tests.sh "${{ inputs.interface }}" "$target_pattern_file" "$cache_test_results" || {
-              res=$?; echo "To reproduce failures locally, follow the instructions at https://opentitan.org/book/doc/getting_started/setup_fpga.html#reproducing-fpga-ci-failures-locally"; exit "${res}";
-            }
-          else
-            echo "No tests to run after filtering"
-          fi
+#      - name: Update hyperdebug firmware
+#        if: inputs.interface == 'hyper310' || inputs.interface == 'cw340'
+#        run: |
+#          ./bazelisk.sh run \
+#              //sw/host/opentitantool:opentitantool -- \
+#              --interface=hyperdebug_dfu transport update-firmware
+#
+#      - name: Execute tests
+#        run: |
+#          . util/build_consts.sh
+#          module load "xilinx/vivado/${{ inputs.vivado_version }}"
+#
+#          cache_test_results="--cache_test_results=${{ inputs.cache_test_results }}"
+#
+#          # Run FPGA tests
+#          if [[ -s "$target_pattern_file" ]]; then
+#            ci/scripts/run-fpga-tests.sh "${{ inputs.interface }}" "$target_pattern_file" "$cache_test_results" || {
+#              res=$?; echo "To reproduce failures locally, follow the instructions at https://opentitan.org/book/doc/getting_started/setup_fpga.html#reproducing-fpga-ci-failures-locally"; exit "${res}";
+#            }
+#          else
+#            echo "No tests to run after filtering"
+#          fi
 
       - uses: actions/checkout@v6
         if: ${{ !cancelled() }}
